Speed up the formula
saltstack-formulas/librenms-formula pull request #8
Opened 2019-05-14 17:38 UTC by alxwr

Instead of `file.directory` with `recurse: ['user', 'group']` the formula now uses `chmod` and `chown` when it is necessary.
This prevents a highly reproducilbe `Minion did not return. [No response]`. :-)

Tested on FreeBSD 11.2.

2019-05-24 14:02 UTC, vutny requested changes
@alxwr I wonder, could we use `file.directory` state function with `recurse` parameter instead of raw chmod/chown commands?

2019-05-24 14:05 UTC, vutny commented
I meant you still can use `onchanges` requisite to not invoke recursive operation on every Salt state run.

2019-05-25 00:03 UTC, alxwr commented
@vutny Thanks for your review!
> @alxwr I wonder, could we use `file.directory` state function with `recurse` parameter instead of raw chmod/chown commands?

`recurse` is extremely slow. Up to the point of "minion did not respond". (I was so glad when I figured out this was the bottleneck! :-)

The only OS (I can think of) where chown/chmod won't work is Windows. I'll wrap the code in `if grains.os_family != 'Windows'`, but I doubt anyone would run LibreNMS on Windows.
We could also enable chown/chmod only for Linux and FreeBSD and use `recurse` for the rest. (But that's not exactly DRY...)

> I meant you still can use `onchanges` requisite to not invoke recursive operation on every Salt state run.

That won't solve the underlying problem. :-(

2019-05-25 08:24 UTC, aboe76 commented
@alxwr if I look at the new installation manuals from https://docs.librenms.org/Installation/

they have abandoned the git clone method and started with composer, shouldn't that solve a lot of problems, running composer as `librenms` should fix the file permissions.

2019-05-25 19:37 UTC, alxwr commented
@aboe76 I'll try that. Thanks!

2023-08-21 12:00 UTC, closed without merging